version: "3.9"

networks:
  app:

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        USER: user
        UID: 1000
        GID: 1000
    command: >
      sh -c "composer install &&
      php artisan serve --host=0.0.0.0"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - database
    restart: on-failure
    networks:
      - app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/code
    environment:
      - NODE_INSTALL=true
    depends_on:
      - backend
    networks:
      - app

  database:
    image: mysql:9.4
    restart: always
    environment:
      MYSQL_DATABASE: financial_tracker
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - app

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: redis-server
    volumes:
      - redis-data:/data
    networks:
      - app

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    restart: on-failure
    networks:
      - app

volumes:
  database_data:
  redis-data: